[package]
name = "login_server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
regex = "1"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }  
